spring:
  application:
    name: config-server
  cloud:
    config:
      label: master  # label 表示 分支：
      server:
        git:
          uri: https://github.com/how2j/springcloudConfig/  # uri 表示 git 地址：
          searchPaths: respo  # searchPaths 表示目录：
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/