spring:
  application:
    name: product-view-service-feign  #指定自己的名称
    zipkin:
      base-url: http://localhost:9411  # 服务链路追踪 zipkin
  thymeleaf:
    cache: false
    prefix: classpath:/templates/ #一些thymeleaf的默认配置
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  zipkin:
    base-url: http://localhost:9411